// <auto-generated />
using System;
using LeDrink.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeDrink.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220314153658_update2")]
    partial class update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("LeDrink.DAL.Models.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BottleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BottleSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bottles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BottleName = "Coca Cola",
                            BottleSlotId = 1
                        },
                        new
                        {
                            Id = 2,
                            BottleName = "Fanta",
                            BottleSlotId = 2
                        },
                        new
                        {
                            Id = 3,
                            BottleName = "RedBull",
                            BottleSlotId = 3
                        },
                        new
                        {
                            Id = 4,
                            BottleName = "Vodka",
                            BottleSlotId = 4
                        });
                });

            modelBuilder.Entity("LeDrink.DAL.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgPath")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("LeDrink.DAL.Models.Mix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DrinkId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Milliliters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BottleId");

                    b.HasIndex("DrinkId");

                    b.ToTable("Mixes");
                });

            modelBuilder.Entity("LeDrink.DAL.Models.Mix", b =>
                {
                    b.HasOne("LeDrink.DAL.Models.Bottle", "Bottle")
                        .WithMany()
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeDrink.DAL.Models.Drink", null)
                        .WithMany("Mixes")
                        .HasForeignKey("DrinkId");

                    b.Navigation("Bottle");
                });

            modelBuilder.Entity("LeDrink.DAL.Models.Drink", b =>
                {
                    b.Navigation("Mixes");
                });
#pragma warning restore 612, 618
        }
    }
}
